장고_최종/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),   #회원가입
    path('login/', views.login_view, name='login'), #로그인
    path('logout/', views.logout_view, name='logout'), #로그인
]

장고_최종/community/urls.py
from django.urls import path
from .post_views import *
from .comment_views import *

app_name = 'community'

urlpatterns = [
    # 게시글 R ----------
    path('', community_list, name='community_list'),
    path('<int:post_id>/', community_detail, name='community_detail'),
    # 게시글 C, U, D
    path('create/', create_post, name='create_post'), #글작성
    path('delete/<int:post_id>/', delete_post, name='delete_post'), #삭제
    path('modify/<int:post_id>/', modify_post, name='modify_post'), #수정
     # 댓글 CRUD ------------
    path('comment/create/post/<int:post_id>/', comment_create, name='comment_create'),
    path('comment/modify/post/<int:comment_id>/', comment_modify, name='comment_modify'),
    path('comment/delete/post/<int:comment_id>/', comment_delete, name='comment_delete'),
]

장고_최종/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('account.urls')),
    path('frige/', include('frige.urls')),
    path("recommend/", include('recommend.urls')),
    path("community/", include('community.urls')),
    path('report/', include('report.urls')),
]

장고_최종/community/models.py
from django.db import models
from account.models import CustomUser
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default='')
    subject = models.CharField('제목', max_length=200)
    content = models.TextField('내용')
    created_at = models.DateTimeField('날짜')
    modify_date = models.DateTimeField(null=True, blank=True)
    
class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default="")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default="")
    content = models.TextField('내용')
    created_at = models.DateTimeField('날짜')
    modify_date = models.DateTimeField(null=True, blank=True)

장고_최종/community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .form import PostForm
from django.utils import timezone
from django.contrib import messages

# Create your views here.
def community_list(request):
    '''
    Community 목록 출력
    '''
    post_list = Post.objects.order_by('-created_at')
    
    context = {
        'post_list' : post_list,
    }
    return render(request, 'community/community_list.html', context)

def community_detail(request, post_id):
    '''
    Community 상세
    '''
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post' : post
    }
    
    return render(request, 'community/community_detail.html', context)

def create_post(request):
    '''
    글 작성
    '''
    if request.method == 'POST':
        form = PostForm(request.POST)
        # 여기서 request.FILES 하고 save 아래에서 하니까 아래 코드 한 줄 필요 없음!
        if form.is_valid():
            problem = form.save(commit=False)
            problem.created_at = timezone.now()
            problem.user = request.user
            problem.save()
            return redirect('community:community_list')
    else:
        form = PostForm()
        
    context = {'form': form}
        
    return render(request, 'community/community_form.html', context)

def delete_post(request, post_id):
    '''
    글 삭제
    '''
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.user:
        messages.error(request, '삭제 권한이 없습니다. . 😅')
        return redirect('community:community_detail', post_id = post.id)
    post.delete()
    return redirect('community:community_list')

def modify_post(request, post_id):
    '''
    글 수정
    '''
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.user:
        messages.error(request, '수정 권한이 없습니다. . 😅')
        return redirect('community:community_detail', post_id = post.id)
    
    if request.method == "POST":
        form = PostForm(request.POST, instance=post) #기존 데이터를 가져온 후 POST 데이터로 덮어씌움
        if form.is_valid():
            post = form.save(commit=False)
            form.user = request.user 
            post.modify_date = timezone.now()
            post.save()
            return redirect('community:community_detail', post_id=post.id)
    else:
        form = PostForm(instance=post)
    context = {'form' : form}
    return render(request, 'community/community_form.html', context)

장고_최종/templates/community/comment_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    {% if user.is_authenticated %}
    <div class="d-flex justify-content-center align-items-center">
        <div class="d-flex justify-content-between mb-3" style="width: 50rem;">
            <form class="d-flex">
                <a href="{% url 'account:logout' %}" class="fw-medium btn me-2" type="button">로그아웃</a>
            </form>
            <a class="mx-2 btn" href = "{% url 'community:community_list' %}">목록보기</a>
        </div>
    </div>
    {% endif %}
    <div class='container my-3'>
        <h5 class='border-bottom pb-2'>
            댓글 수정 하기 🍷
        </h5>
        <form method='post' class = 'post-form my-3' enctype="multipart/form-data">
            {% csrf_token %}
            {%bootstrap_form form%}
            <!--{{form.as_p}} as_p : <p>태그로 묶어서 입력을 보내겠다는 의미-->
                
            <!--Post_form.html-->
            {% block style %}
            <link rel = 'stylesheet' href = " {% static 'summernote-bs4.min.css' %}">
            {% endblock style %}

            {% block script %}
            <script src = "{% static 'summernote-ko-KR.min.js' %}"></script>

            <script>
                $(function() {
                    //SummberNote
                    $('#id_content').summernote({
                        height:300
                    })
                })
            </script>
            {% endblock script %}

            <button type='submit' class="btn btn-primary"> 저장하기 </button>
        </form>
    </div>
{% endblock content %}

장고_최종/templates/community/comment_list.html
<!--Comment Line-->
<div style = "font-size: small">
    {% if post.comment_set.count > 0 %}
        {% for comment in post.comment_set.all %}
            <div style = 'padding: 20px 10px 20px 10px;'>
                {% if comment.user == post.user %} <strong style = 'color:#eb5d56'>[작성자]</strong>{% endif %} <strong>{{comment.user.username}}</strong>
                {% if comment.modify_date %}
                    <div style = "color:#c3c4c4">{{comment.modify_date}}(수정됨)</div>
                {% else %}
                    <div style = "color:#c3c4c4">{{comment.create_date}}</div>
                {% endif %}
                <div style = 'padding-left : 30px; padding-right : 30px;'> 
                    {{comment.content}} 
                    {% if request.user == comment.user %}
                    <div class = 'd-flex justify-content-end'>
                        <a href = "{% url 'community:comment_modify' comment.id %}" class="btn btn-outline-secondary" role="button" style = "margin: 0px 2px">수정</a>
                        <a href="#" data-uri = "{% url 'community:comment_delete' comment.id %}" class="delete_comment btn btn-outline-danger" role="button" style = "margin: 0px 2px">삭제</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>

장고_최종/templates/community/community_detail.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="d-flex justify-content-center align-items-center">
    <div class="d-flex justify-content-between mb-3" style="width: 50rem;">
        <form class="d-flex">
            <a href="{% url 'account:logout' %}" class="fw-medium btn me-2" type="button">로그아웃</a>
        </form>
        <a class="mx-2 btn" href = "{% url 'community:community_list' %}">목록보기</a>
    </div>
</div>
{% endif %}

<h2 class = "border-bottom py-2">
    <i class="fa-solid fa-person-circle-question"></i>
    {{post.subject}}
</h2>
<span>
    작성자 : 
    <strong>
        {{post.user.username}}
    </strong>
</span>
{% if request.user == post.user %}
        <span class='mx-3'>
            <a href ="{% url 'community:modify_post' post.id  %}" class='btn btn-dark'>수정</a>
        </span>
        <span >
            <a href ='#' class='delete btn btn-sm btn-danger' data-uri = "{% url 'community:delete_post' post.id %}">삭제</a>
        </span>
    {% endif %}
<!--card 를 이용하여 사진 등 첨부 가능 : ex. youtube 썸네일-->
<div class = "card my-3">
    <div class = "card-body">
        <!--white space : 공백, 개행 등등 을 작성한 그대로-->
        <div class = "card-text" style = "white-space : pre-line;">
            {{post.content}}
        </div>
        <!--float와 비슷하게 정렬-->
        <div class = "d-flex justify-content-end">
            <!--badge : 사각형으로 둘러쌈-->
            <div class = "badge badge-light p-2">
                <div class = "badge badge-light p-2 text-left mx-3">
                    {% if post.modify_date %}
                        <div> {{post.modify_date}} <small>에 수정됨</small></div> 
                    {% else %}
                        <div> {{post.created_at}} </div>
                    {% endif %}
                    </div>
            </div>
        </div>
    </div>
</div>

{% include './comment_list.html' %}
<form action="{% url 'community:comment_create' post.id %}" method="post">
    {% comment %} <form action="" method="post"> {% endcomment %}
        {% csrf_token %}
        {% if form.errors %}
        <div class = "alert alert-danger" role = "alert">
            {% for field in form %}
                {% if field.errors and field.label == '답변 내용'%}
                    <strong>{{field.label}}</strong>
                    {{field.errors}}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <div class = "form-group"> <!-- 로그인 없이 답변 불가-->
            <textarea {% if not user.is_authenticated %} disabled='disabled'{% endif %} 
            name="content" id="content" class = 'form-control' rows="8"></textarea>
        </div>
        <input {% if not user.is_authenticated %} disabled='disabled'{% endif %} 
        type="submit" value="답변등록" class = 'btn btn-secondary'>
    </form> 
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        /* Delete */
        $(".delete").on("click", function() {
            console.log("Click")
            if (confirm("정말로 삭제 하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
        $(".delete_comment").on("click", function() {
          if (confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
          }
        });
    });
</script>
{% endblock script %}

장고_최종/templates/community/community_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
    <div class="d-flex justify-content-center align-items-center">
        <div class="d-flex justify-content-between mb-3" style="width: 50rem;">
            <form class="d-flex">
                <a href="{% url 'account:logout' %}" class="fw-medium btn me-2" type="button">로그아웃</a>
            </form>
            <a class="mx-2 btn" href = "{% url 'community:community_list' %}">목록보기</a>
        </div>
    </div>
    {% endif %}

    <div class = "container">
        <h5 class = "my-3 border-bottom pb-2">
            <i class="fa-solid fa-thumbtack"></i>
            글 작성
        </h5> 
        <form method="post" class="post-form my-3">
            {% csrf_token %}
            {%bootstrap_form form%}

            <div>
                <button type="submit" class = "btn btn-success mt-2">
                <i class="fa-regular fa-paper-plane"></i>
                게시글 업로드
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

장고_최종/templates/community/community_list.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="d-flex justify-content-center align-items-center">
    <div class="d-flex justify-content-between mb-3" style="width: 50rem;">
        <form class="d-flex">
            <a href="{% url 'account:logout' %}" class="fw-medium btn me-2" type="button">로그아웃</a>
        </form>
    </div>
</div>
{% endif %}

<div class="d-flex justify-content-center align-items-center">
    <h2>커뮤니티</h2>
</div> 
<div>
    {% if post_list %}
        {% for post in post_list %}
            <div class = "card">
                <div class = "card-title">
                    <h2 style="margin-top:20px; margin-left:15px">
                        <a href = "{% url 'community:community_detail' post.id %}" style = "text-decoration:none; color: inherit;" >{{post.subject}}</a>
                    </h2>
                </div>
                <div class = "card-body" style = "display : -webkit-box; -webkit-line-clamp : 3; -webkit-box-orient : vertical;">
                    <a href = "{% url 'community:community_detail' post.id %}" style = "text-decoration:none; color: inherit;" >
                        {{post.content|striptags|cut:"&nbsp;" }}
                    </a>
                    <div class = "d-flex justify-content-end">
                        <!--badge : 사각형으로 둘러쌈-->
                        <div class = "badge badge-gray p-2">
                            {{post.user.username}}
                        </div>
                        <div class = "badge badge-light p-2">
                            {% if post.modify_date %}
                                <div> {{post.modify_date}} <small>에 수정됨</small></div> 
                            {% else %}
                                <div> {{post.created_at}} </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>게시글이 없습니다.</p>
    {% endif %}
</div>

<div class='d-flex flex-row-reverse mb-3'>
    <a href="{% url 'community:create_post' %}" class='btn'>
      <i class="fa-regular fa-note-sticky"></i>
      글작성
    </a>
</div>

{% endblock content %}

{% block script %}
<script type="text/javascript">
{% endblock script %}