장고_최종/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('account.urls')),
    path('frige/', include('frige.urls')),
    path("recommend/", include('recommend.urls')),
    path("community/", include('community.urls')),
    path('report/', include('report.urls')),
]

장고_최종/recommend/urls.py
from django.urls import path
from . import views

app_name = 'recommend'

urlpatterns = [
    path('', views.index, name='index'),
    path('weather/', views.weather, name="search"),
    # path('', frige_list, name='frige_list'),
]

장고_최종/templates/recc/search_rec.html
{% extends 'base.html' %}
{% block content %}
<form method="get" action="{% url 'recommend:index' %}">
    <div class="input-group mb-3">
        <input id="alco" name="alco" placeholder="주류명을 입력하세요" type="text" value="{{ request.GET.alco }}" class="form-control" style = "width:100px">
        <div class="input-group-append">
            <button class="btn btn-success" type="submit">추천</button>
        </div>
    </div>
</form>  
<br>
{% if result %}        
    전체 주류내에서 추천 
    <ul>
    {% for item in result.general %}
        <div>{{ item }}</div>
        {% if forloop.counter|divisibleby:6 and not forloop.last %}
        <hr style="border-top: 1px dashed black; margin: 10px 0;"> <!-- 수정된 부분: 6번째 정보마다 선 추가 -->
        {% endif %}
    {% endfor %}
    </ul>
    
    <br>
    <hr style="border-top: 1px solid black; margin: 10px 0;">
    같은 주류내에서 추천 
    <ul>
    {% for item in result.alc_cate %}
        <div>{{ item }}</div>
        {% if forloop.counter|divisibleby:8 and not forloop.last %}
        <hr style="border-top: 1px dashed black; margin: 10px 0;"> <!-- 수정된 부분: 8번째 정보마다 선 추가 -->
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
<div>검색어를 입력하세요.</div> <!-- 검색어를 입력하지 않았을 때 메시지 표시 -->

{% endif %}

{% endblock %} 

장고_최종/templates/recc/weather_rec.html
{% extends 'base.html' %}
{% block content %}
<form method="get" action="{% url 'recommend:search' %}">
    <div class="input-group mb-3">
        <input value="{{city}}" id="city" name="city" placeholder="Search by City" type="text" class="form-control"style = "width:100px">
        <div class="input-group-append">
          <button class="btn btn-success" type="submit">검색</button>
        </div>
      </div>
    <div>
</form>
<div>
    <p>선택한 지역 <a class = "text-info">{{ city }}</a></p>
    <p>날씨 <a class = "text-info">{{ weather }}</a></p>
</div>
{% for rec in recc %}
    {% for r in rec %}
    <div>{{r}}</div>
    {% if forloop.counter|divisibleby:7 and not forloop.last %}
    <hr style="border-top: 1px solid black; margin: 10px 0;"> <!-- 수정된 부분: 7번째 정보마다 선 추가 -->
    {% endif %}
    {% endfor %}
{% endfor %}

{% endblock %}