장고_최종/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),   #회원가입
    path('login/', views.login_view, name='login'), #로그인
    path('logout/', views.logout_view, name='logout'), #로그인
]

장고_최종/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('account.urls')),
    path('frige/', include('frige.urls')),
    path("recommend/", include('recommend.urls')),
    path("community/", include('community.urls')),
    path('report/', include('report.urls')),
]

장고_최종/frige/urls.py
from django.urls import path
from .views import frige_list, frige_state, handle_quantity

app_name = 'frige'

urlpatterns = [
    path('', frige_list, name='frige_list'),
    path('<int:frige_id>/', frige_state, name='frige_state'),
    path('quantity/', handle_quantity, name='handle_quantity'),
    path('delete/', frige_list, name='frige_delete'),
]

장고_최종/frige/models.py
from django.db import models
from account.models import CustomUser

class Frige(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255) #영문숫자
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Drink(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255) # mysql에서 한글로 바꿔줘야함
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    frige = models.ForeignKey(Frige, on_delete=models.CASCADE, related_name='drinks')
    quantity = models.PositiveIntegerField(default=0)

class Log(models.Model):
    id = models.AutoField(primary_key=True)
    frigename = models.CharField(max_length=255) 
    drinkname = models.CharField(max_length=255) # mysql에서 한글로 바꿔줘야함
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


# class FrigeItem(models.Model):
#     frige = models.ForeignKey(Frige, on_delete=models.CASCADE, related_name='items')
#     drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField(default=0)
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

장고_최종/frige/forms.py
from django import forms
from .models import Frige

class FrigeForm(forms.ModelForm):
    class Meta:
        model = Frige
        fields = ['name']

장고_최종/frige/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FrigeForm
from .models import Frige, Drink
from django.contrib.auth.decorators import login_required
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# MQTT 통신
import account.views as account

# MQTT 연결
client = account.client
_topic = "refri/"

# Create your views here.

# 냉장고 등록 및 리스트 frige:frige_list  
# @login_required
def frige_list(request):
    user = request.user
    friges = Frige.objects.filter(user=user)
    form = FrigeForm()
    
    client.publish(f"{_topic}refriname", "")
    print("Topic : {}, Refri : {}".format(f"{_topic}refriname", "main"))

    if request.method == 'POST':
        form = FrigeForm(request.POST)
        if form.is_valid():
            frige = form.save(commit=False)
            frige.user = user
            frige.save()
            return redirect('frige:frige_list')
    #추가
    if request.method == 'GET' and 'delete_frige_id' in request.GET:
        delete_frige_id = request.GET.get('delete_frige_id')
        try:
            frige_to_delete = Frige.objects.get(id=delete_frige_id, user=user)
            frige_to_delete.delete()
            return redirect('frige:frige_list')
        except Frige.DoesNotExist:
            pass
    context = {
        'friges': friges,
        'form': form
    }
    return render(request, 'frige/frige_list.html', context)

# @login_required
# def frige_list(request):
#     user = request.user
#     if user.is_authenticated:  # 인증된 사용자인지 확인
#         friges = Frige.objects.filter(user=user)
#     else:
#         friges = None

#     form = FrigeForm()

#     if request.method == 'POST':
#         form = FrigeForm(request.POST)
#         if form.is_valid():
#             frige = form.save(commit=False)
#             frige.user = user
#             frige.save()
#             return redirect('frige:frige_list')

#     context = {
#         'friges': friges,
#         'form': form
#     }
#     return render(request, 'frige/frige_list.html', context)

# 냉장고 상태 및 주류 품목 조절
# @login_required
def frige_state(request, frige_id):
    frige = get_object_or_404(Frige, id=frige_id, user=request.user)
    drinks = frige.drinks.all()
    current_frige_id = frige.id  # 현재 페이지의 냉장고 ID
    
    client.publish(f"{_topic}refriname", frige.name)
    print("Topic : {}, Refri : {}".format(f"{_topic}refriname", frige.name))

    user = request.user
    friges = Frige.objects.filter(user=user)

    context = {
        'frige': frige,
        'drinks': drinks,
        'friges': friges,
        'current_frige_id': current_frige_id,  # 현재 페이지의 냉장고 ID 변수를 전달
    }
    return render(request, 'frige/frige_state.html', context)

# 수량조절 
@csrf_exempt
def handle_quantity(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body.decode('utf-8'))
            drink_id = data.get('drink_id')
            quantity = data.get('quantity')

            if drink_id is not None and quantity is not None:
                try:
                    drink = Drink.objects.get(id=drink_id)
                    drink.quantity = quantity
                    drink.save()
                    return JsonResponse({'status': 'success', 'result': drink.quantity})
                except Drink.DoesNotExist:
                    return JsonResponse({'status': 'error', 'message': 'Item not found.'})
            else:
                return JsonResponse({'status': 'error', 'message': 'Invalid JSON data.'})

        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Invalid JSON data.'})

    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})

장고_최종/templates/frige/frige_list.html
{% extends 'base.html' %}

<!-- 메인화면  -->
{% block content %}
{% if user.is_authenticated %}
<div class="d-flex justify-content-center align-items-center">
    <div class="d-flex justify-content-between mb-3" style="width: 50rem;">
        <form class="d-flex">
            <a href="{% url 'account:logout' %}" class="fw-medium btn me-2" type="button">로그아웃</a>
        </form>
        <a class="mx-2 btn" href="{% url 'frige:frige_list'%}">메인으로 가기</a>
    </div>
</div>
{% endif %}

<div class="d-flex justify-content-center align-items-center">
  <div style="width: 50rem;">
      <!-- 등록된 냉장고 있는 경우 -->
      {% if friges %}
        <h4 class="text-center mb-4 mt-4">냉장고 List</h4>
          <!-- 냉장고 리스트 출력 -->
          <div class="row justify-content-center">
            {% for frige in friges %}
              <div class="col-sm-7 mb-3">
                <a class="btn btn-outline-success w-100" href="{% url 'frige:frige_state' frige.id %}">
                  {{ frige.name }}
                </a>
              </div>
              <!-- 추가 -->
              <!-- 냉장고 삭제 링크 -->
              <a href="{% url 'frige:frige_list' %}?delete_frige_id={{ frige.id }}">냉장고 삭제</a>
            {% endfor %}
          </div>
          <hr>
          <!-- 냉장고 추가 등록 -->
          <p class="text-center mb-4">냉장고 추가 등록</p>
          <div class="row justify-content-center">
            <form method="POST">
              {% csrf_token %}
                <div class="row mb-4">
                  <div class="col-sm-5">
                    <label for="{{ form.name.id_for_label }}" >냉장고 이름 </label>
                    <p><small class="text-muted">*내부 라벨에 적힌 ID 입력</small></p>
                  </div>
                  <div class="col-sm-7">{{ form.name }}</div>
                </div>
                <div class="d-flex justify-content-center align-items-center mt-3">
                  <button type="submit" class="btn btn-success">추가</button>
                </div>
            </form>
          </div>
      <!-- 등록된 냉장고 없는 경우 -->
      {% else %}
        <h4 class="text-center mb-4 mt-4">냉장고 List</h4>
        <div class="text-center row justify-content-center mb-4 mt-4">
          <div class="card col-sm-5">
            <div class="card-body text-center display-5">
              등록된 냉장고가 없습니다ㅠ
            </div>
          </div>
        </div>
        <hr>
        <!-- 냉장고 등록 -->
        <h4 class="text-center mt-4">냉장고 등록</h4>
        <div class="row justify-content-center">
          <form method="POST">
            {% csrf_token %}
              <div class="row ">
                <div class="col-sm-5 ">
                  <label for="{{ form.name.id_for_label }}" >냉장고 이름</label>
                  <p><small class="text-muted">*내부 라벨에 적힌 ID 입력</small></p>
                </div>
                <div class="col-sm-7">{{ form.name }}</div>
              </div>
              <div class="d-flex justify-content-center align-items-center mt-3">
                <button type="submit" class="btn btn-outline-success">추가</button>
              </div>
          </form>
        </div>
      {% endif %}
      <hr>
      <!-- 다른 탭 -->
      {% comment %} <div class="row justify-content-center mt-2">
        <!-- 안주추천 -->
        <div class="col-sm-7 mb-4">
          <a class="btn btn-outline-success w-100" href="#">
            안주 추천
          </a>
        </div>
        <!-- 주류 추천 -->
        <div class="col-sm-7 mb-4">
          <a class="btn btn-outline-success w-100" href="#">
            주류 추천
          </a>
        </div>
        <!-- 커뮤니티 -->
        <div class="col-sm-7 mb-4">
          <a class="btn btn-outline-success w-100" href="#">
            커뮤니티
          </a>
        </div>
      </div> {% endcomment %}
  </div>
</div>
{% endblock %}

장고_최종/templates/frige/frige_state.html
{% extends 'base.html' %} 

{% block content %}
{% if user.is_authenticated %}
<div class="d-flex justify-content-center align-items-center">
    <div class="d-flex justify-content-between mb-3" style="width: 50rem;">
        <form class="d-flex">
            <a href="{% url 'account:logout' %}" class="fw-medium btn me-2" type="button">로그아웃</a>
        </form>
        <a class="mx-2 btn" href="{% url 'frige:frige_list'%}">메인으로 가기</a>
    </div>
</div>
{% endif %}

<div class="d-flex justify-content-center align-items-center">
    <div style="width: 50rem;">
        <br><br>
        {% if friges %}
        <div class="row justify-content-start">
            <h5 class="mx-4 pt-2">냉장고 list</h5>
            {% for frige in friges %}
                <div class="mb-4">
                {% if frige.id == current_frige_id %}
                    <a class="mx-2 btn btn-success disabled" href="{% url 'frige:frige_state' frige.id %}">
                        {{ frige.name }}
                    </a>
                {% else %}
                    <a class="mx-2 btn btn-outline-success" href="{% url 'frige:frige_state' frige.id %}">
                        {{ frige.name }}
                    </a>
                {% endif %}
                </div>
            {% endfor %}
        {% endif %}
        </div>
        <div class="card mt-3 mb-5">
            <div class="card-body">
                <h5 id="frige_id" class="card-title">냉장고 id {{ frige.id }}</h5>
                <h6 class="card-subtitle mb-2 text-muted"> 이름 {{ frige.name }}</h6>
                <h3>주류 목록</h3>
                <ul>
                    {% for drink in drinks %}
                        <li>
                            <p>{{ drink.name }}</p>
                            <div class="quantity">
                                <a href="#" class="minus" data-drink-id="{{ drink.id }}">-</a>
                                <span id="result_{{ drink.id }}" class="result" data-drink-id="{{ drink.id }}">{{ drink.quantity }}</span>
                                <a href="#" class="plus" data-drink-id="{{ drink.id }}">+</a>
                            </div>
                        </li>
                    {% empty %}
                        <li>등록된 주류가 없습니다.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <a onClick="window.location.reload()">새로고침<i class="fa-solid fa-rotate-right"></i></a>
    </div>
</div>

{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".minus").click(function(e) {
            e.preventDefault();
            var drinkId = $(this).data("drink-id");
            var resultElement = $("#result_" + drinkId);
            var quantity = parseInt(resultElement.text());
            if (quantity > 0) {
                quantity--;
                resultElement.text(quantity);
                updateQuantity(drinkId, quantity);
            }
        });

        $(".plus").click(function(e) {
            e.preventDefault();
            var drinkId = $(this).data("drink-id");
            var resultElement = $("#result_" + drinkId);
            var quantity = parseInt(resultElement.text());
            quantity++;
            resultElement.text(quantity);
            updateQuantity(drinkId, quantity);
        });

        function updateQuantity(drinkId, quantity) {
            var url = "{% url 'frige:handle_quantity' %}";
            var data = {
                drink_id: drinkId,
                quantity: quantity
            };

            $.ajax({
                type: "POST",
                url: url,
                data: JSON.stringify(data),
                contentType: "application/json",
                success: function(response) {
                    console.log("data pass success", response);
                    if (response.status === "success") {
                        $("#result").text(response.result);
                    } else {
                        console.log("Error: " + response.message);
                    }
                },
                error: function(xhr, errmsg, err) {
                    console.log(xhr.status + ": " + xhr.responseText);
                }
            });
        }
    });
</script>

{% endblock script %}